export const TOGGLE_ACTIVE_LAYER_MAP = 'TOGGLE_ACTIVE_LAYER_MAP';
export const ADD_MARKER_MAP = 'ADD_MARKER_MAP';
export const REMOVE_MARKER_MAP = 'REMOVE_MARKER_MAP';
export const RESET_ACTIVE_LAYER_MAP = 'RESET_ACTIVE_LAYER_MAP';
