export const LOAD_LAYERS = 'LOAD_LAYERS';
export const SET_LAYERS = 'SET_LAYERS';
export const REMOVE_ITEM_LAYERS = 'REMOVE_ITEM_LAYERS';
export const CHANGE_ITEM_NAME_LAYERS = 'CHANGE_ITEM_NAME_LAYERS';
export const ADD_ITEM_LAYERS = 'ADD_ITEM_LAYERS';
export const SET_ITEM_MARKERS_LAYERS = 'SET_ITEM_MARKERS_LAYERS';
export const SAVE_LAYER_CHANGES_LAYERS = 'SAVE_LAYER_CHANGES_LAYERS';
